//First screen to pop up when you run the code
package coe528project;
import javax.swing.JOptionPane;
import javax.swing.*;


public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public static Owner theOwner; 
    public LoginScreen() {
        initComponents();
        theOwner = new Owner(); 
        theOwner.loadCustomersFromFile(); 
        theOwner.loadBooksFromFile(); 
        setTitle("Book Store App");  //Sets the title
        ImageIcon icon = new ImageIcon(getClass().getResource("/book.png"));
        setIconImage(icon.getImage());
        getContentPane().setBackground(new java.awt.Color(92, 64, 51));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginScreenUsernameText = new javax.swing.JLabel();
        loginScreenPasswordText = new javax.swing.JLabel();
        loginScreenTitle = new javax.swing.JLabel();
        enteredUsername = new javax.swing.JTextField();
        enteredPassword = new javax.swing.JPasswordField();
        showPasswordCheckBox = new javax.swing.JCheckBox();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        loginScreenUsernameText.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        loginScreenUsernameText.setForeground(new java.awt.Color(244, 225, 193));
        loginScreenUsernameText.setText("Username");

        loginScreenPasswordText.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        loginScreenPasswordText.setForeground(new java.awt.Color(244, 225, 193));
        loginScreenPasswordText.setText("Password");

        loginScreenTitle.setBackground(new java.awt.Color(244, 225, 193));
        loginScreenTitle.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        loginScreenTitle.setForeground(new java.awt.Color(244, 225, 193));
        loginScreenTitle.setText("Book Store Login");

        enteredUsername.setBackground(new java.awt.Color(244, 225, 193));
        enteredUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 225, 193), 3, true));
        enteredUsername.setDisabledTextColor(new java.awt.Color(92, 64, 51));

        enteredPassword.setBackground(new java.awt.Color(244, 225, 193));
        enteredPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(244, 225, 193), 3, true));
        enteredPassword.setDisabledTextColor(new java.awt.Color(92, 64, 51));

        showPasswordCheckBox.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        showPasswordCheckBox.setForeground(new java.awt.Color(244, 225, 193));
        showPasswordCheckBox.setText("Show password");
        showPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordCheckBoxActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(244, 225, 193));
        loginButton.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        loginButton.setForeground(new java.awt.Color(92, 64, 51));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginScreenTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginScreenUsernameText)
                            .addComponent(loginScreenPasswordText)
                            .addComponent(showPasswordCheckBox))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(enteredPassword)
                            .addComponent(enteredUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(loginScreenTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginScreenUsernameText)
                    .addComponent(enteredUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginScreenPasswordText)
                    .addComponent(enteredPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showPasswordCheckBox)
                    .addComponent(loginButton))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordCheckBoxActionPerformed
        // TODO add your handling code here:
        if(showPasswordCheckBox.isSelected()){
            enteredPassword.setEchoChar((char) 0);
        }
        else{
            enteredPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordCheckBoxActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = enteredUsername.getText();
        String password = new String(enteredPassword.getPassword());

        // Check for admin login
        if (username.equals("admin") && password.equals("admin")) {
            new OwnerOptionsPage().setVisible(true);  // Show owner options page
            this.dispose();  // Close the login page
            return;  // Exit the method 
        }

        // If it's not admin, check for customer login
        boolean loginSuccess = false;
        Customer loggedInCustomer = null; // Variable to store the logged-in customer

        for (Customer customer : Owner.customers) {
            if (customer.getUsername().equals(username)) {  // Check if the username exists
                String actualPassword = customer.getPassword();  // Retrieve the actual password
                if (actualPassword.equals(password)) {  // Check if the password matches
                    loginSuccess = true;  // Successful login
                    loggedInCustomer = customer;  // Store the logged-in customer object
                    break;
                }
            }
        }

        if (loginSuccess) {
            // Customer login successful
            // Pass the customer data to CustomerBookPage
            String status = loggedInCustomer.getStatus();  // Assuming Customer has getStatus() method
            int points = loggedInCustomer.getPoints();  // Assuming Customer has getPoints() method
            new CustomerBookPage(username, points, status).setVisible(true);  // Show CustomerBookPage with data
            this.dispose();  // Close the login page
        } else {
            // Incorrect username or password
            JOptionPane.showMessageDialog(this, "Invalid username or password.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField enteredPassword;
    private javax.swing.JTextField enteredUsername;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginScreenPasswordText;
    private javax.swing.JLabel loginScreenTitle;
    private javax.swing.JLabel loginScreenUsernameText;
    private javax.swing.JCheckBox showPasswordCheckBox;
    // End of variables declaration//GEN-END:variables
}
